services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  rabbitmq-service:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
    expose:
      - "8080"
    networks:
      - default

  redis-service:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    expose:
      - "8080"
    networks:
      - default

  auction-service:
    image: marke01/auction-service:latest
    ports:
      - 5230:8080
    environment:
      - redisConnection=redis-16065.c56.east-us.azure.redns.redis-cloud.com:16065,password=1234
      - rabbitmqUrl=rabbitmq-service
      - rabbitmqPort=5672
      - Valid=http://auth-service:8080
    expose:
      - "8080"
    networks:
      - loki

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27018:27017
    expose:
      - "8080"
    networks:
      - loki

  user-service:
    image: marke01/user-service:latest
    ports:
      - 5102:8080
    environment:
      - connectionString=mongodb://mongodb:27017/
      - userCol=userCol
      - database=userDB
    expose:
      - "8080"
    networks:
      - loki

  auth-service:
    image: marke01/auth-service:latest
    ports:
      - 5049:8080
    environment:
      - Secret=RasmusGrønErSuperCoolOgDenBedsteChef!
      - Issuer=Gron&OlsenGruppen
      - apiGetUser=user-service:80/user/GetUser
      - Valid=http://auth-service:8080
    expose:
      - "8080"
    networks:
      - loki

  catalog-service:
    image: marke01/catalog-service:latest
    ports:
      - 5289:8080
    environment:
      - connectionString=mongodb://mongodb:27017/
      - collection=catalogCol
      - AuctionConnection=http://auction-service:8080
      - database=catalogDB
    networks:
      - loki

  bid-service:
    image: marke01/bid-service:latest
    environment:
      - mongodb=mongodb://mongodb:27017/
      - database=auctionDB
      - collection=auctionBidCol
      - rabbitmqUrl=rabbitmq-service
      - rabbitmqPort=5672
    networks:
      - loki

networks:
  loki:
  default:
